import "@/app/styles/globals.scss";
import "@/app/styles/theme.scss";
import ToastProvider from "@/provider/toast-provider/toast-provider";
// import Footer from "@/components/layout/footer/footer";
// import Header from "@/components/layout/header/header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the CSS
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
//import Head from "next/head";
import { Suspense } from "react";
//import { GoogleAnalytics } from "@next/third-parties/google";
//import { GoogleTagManager } from '@next/third-parties/google'

import Script from 'next/script';

config.autoAddCss = false;

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Upficient ClickUp Workspaces | Project Management Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
     <head>
        <meta property="og:title" content="Upficient" />
        <meta
          name="google-site-verification"
          content="7A3fj-UIPzZxjzvRAJl21qHD81T2RZekt1LgbG8oR9U"
        />

 	<Script
          id="gtm-loader"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){
                w[l]=w[l]||[];
                w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});
                var f=d.getElementsByTagName(s)[0],
                    j=d.createElement(s);
                j.async=true;
                j.src="https://up.upficient.com/cfjvnkyzzsbh.js?"+i;
                f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','8=AQZOPS40RlswVClNLjFdSB5fQVRLXw8AVRcDHBMaAgsGFl0ZFRQ%3D');
            `,
          }}
        />

      </head>
      <body suppressHydrationWarning={true}>
	
	<Suspense>
          <ToastProvider>
            <main className="wrapper-main">{children}</main>
          </ToastProvider>
        </Suspense>
      </body>
    </html>
  );
}
