import "@/app/styles/globals.scss";
import "@/app/styles/theme.scss";
import ToastProvider from "@/provider/toast-provider/toast-provider";
// import Footer from "@/components/layout/footer/footer";
// import Header from "@/components/layout/header/header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the CSS
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { Suspense } from "react";
import { GoogleAnalytics } from "@next/third-parties/google";
config.autoAddCss = false;

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Upficient ClickUp Workspaces | Project Management Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <Head>
        <meta property="og:title" content="Upficient" />
        <meta
          name="google-site-verification"
          content="7A3fj-UIPzZxjzvRAJl21qHD81T2RZekt1LgbG8oR9U"
        />
      </Head>
      <GoogleAnalytics gaId="G-CQ1YKVRY0H" />
      <body suppressHydrationWarning={true}>
        <Suspense>
          <ToastProvider>
            <main className="wrapper-main">{children}</main>
          </ToastProvider>
        </Suspense>
      </body>
    </html>
  );
}
